replicaCount: 2

image:
  repository: rossdocker123/simpleapi-demo-2026
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: hello-web.local
  path: /

content:
  indexHtml: |
    <h1>Hello from Helm</h1>
    <p>This page is served by nginx, content comes from a ConfigMap.</p>

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
