apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-web.fullname" . }}
  labels:
    {{- include "hello-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "hello-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
    name: http
